name: Coverage

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y lcov gcovr

      - name: Build with coverage flags
        run: |
          mkdir build && cd build
          g++ -std=c++20 -O0 -g -fprofile-arcs -ftest-coverage -fno-inline \
            -I../include ../TestCoroutine.cpp -o CodeConvergeTest

      - name: Run tests
        run: |
          cd build
          ./CodeConvergeTest

      - name: Generate LCOV report
        run: |
          cd build
          gcovr -r .. \
            --exclude-throw-branches \
            --exclude-lines-by-pattern "^\s*assert\s*\(" \
            --object-directory . \
            --lcov --output coverage.info

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: build/coverage.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
