name: Coverage

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install coverage tools
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov gcovr

      - name: Compile with coverage flags
        shell: bash
        run: |
          mkdir build && cd build
          g++ -std=c++20 -O0 -g -fprofile-arcs -ftest-coverage -fno-inline \
            -I../include ../TestCoroutine.cpp -o CodeConvergeTest

      - name: Run executable
        shell: bash
        run: |
          cd build
          ./CodeConvergeTest

      - name: Generate coverage report
        shell: bash
        run: |
          cd build
          gcovr -r .. --exclude-throw-branches --exclude-lines-by-pattern "^\\s*assert\\s*\\(" \
            --object-directory . --html --html-details --output coverage.html
          gcovr -r .. --exclude-throw-branches --exclude-lines-by-pattern "^\\s*assert\\s*\\(" \
            --object-directory . --xml --output coverage.xml

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/coverage.html
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: build/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true